Initech/urls.py
from django.conf.urls import url, include
from django.contrib import admin


app_name = "interview"
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('interview.urls', namespace='interview')),

]

interview/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^login/', LoginView.as_view(), name="login"),
    url(r'^layout/', LayoutView.as_view(), name="layout"),
    url(r'^$', LoginView.as_view(), name="login"),
    url(r'^logout/', LogoutView.as_view(), name="logout"),
    url(r'^sorting/', SortingView.as_view(), name="sorting"),
]

interview/models.py
from django.conf import settings
from django.db import models

class User(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='user')

interview/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=300, widget=forms.TextInput(attrs={'style': "width: 40%;"}))
    password = forms.CharField(max_length=300, widget=forms.PasswordInput(attrs={'style': "width: 40%;"}))

interview/views.py
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.template.response import TemplateResponse
from django.urls.base import reverse
from django.views.generic.base import View
from django.views.generic import FormView
from django.contrib.auth import authenticate, login, logout
import time
import decimal

from interview.forms import LoginForm


class LoginView(FormView):
    form_class = LoginForm
    template_name = "login.html"
    page_title = "Login"

    # Checks if user is already logged in
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('interview:sorting')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'])

        if user is not None and user.is_active:
            login(self.request, user)
            return redirect('interview:sorting')

        # Returns an error if authentication failed
        form.add_error(None, "Invalid user name or password")
        return self.form_invalid(form)


# User Logout
class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('interview:login'))


# Check for user's session and redirects it to the log in page if not authenticated
class LoggedInMixin:
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            url = reverse("interview:login")
            return redirect(url)
        return super().dispatch(request, *args, **kwargs)


class SortingView(LoggedInMixin, View):
    template_name = "sorting.html"
    #Getting via POST the ajax call, reordering it and sleeps for 3 seconds.
    def post(self, request, *args, **kwargs):
        if request.method == 'POST' and request.is_ajax():
            arr = []
            resp = request.POST.get('num1').split(',')
            for i in resp:
                arr.append(decimal.Decimal(i))
            arr.sort()
            time.sleep(3)

        return JsonResponse(arr, safe=False)

    def get(self, request, *args, **kwargs):
        return render(request, "sorting.html")

class LayoutView(View):
    template_name = "Layout.html"

    def get(self, request):
        return TemplateResponse(request, "Layout.html")

interview/templates/Layout.html
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title> CSS Layout </title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Aref+Ruqaa|Space+Mono" rel="stylesheet">
<style>
	a:hover, a:visited, a:link, a:active, a:focus {
    	text-decoration: none;
    	color: black;
	}

	body {
		background-color: #333;
	}

	section {
		margin-left: 300px;
		min-width: 300px;
		overflow: auto;
	}

	section > p {
		font-family: 'Space Mono', monospace;
		font-size: 16px;
		color: #FFFFFF;
		padding-left: 5px;
	}

	nav {
		position: absolute;
		left: 0;
		width: 300px;
		height: auto;
		font-family: 'Aref Ruqaa', sans-serif;
		font-size: 3em;
		background-color: #FFCF75;
	}

	nav ul {
		 list-style: none;
	}

	nav ul li {
		font-size: 1.2em;		
	}

	nav ul li a {
		color: black;
		border-bottom: 0px white;
	}

	nav ul li a:hover {
		border-bottom: 4px solid white;
		color: black;
		transition: .2s;
		-webkit-transition: .2s;
  		-moz-transition: .2s;
  		-o-transition: .2s;
	}

	#clickme {
		position: absolute;
		margin-left: 50%;
	}

	#mynav {
		visibility: visible;
	}

	.btn {
  		cursor: pointer;
  		margin: 10px;
  		border-radius: 5px;
  		text-decoration: none;
  		padding: 10px;
  		font-size: 24px;
  		transition: .3s;
  		-webkit-transition: .3s;
  		-moz-transition: .3s;
  		-o-transition: .3s;
  		display: inline-block;
  		background-color: #333;
	}


	.orange {
  		color: #FFCF75;
  		border: 2px #FFCF75 solid;
	}

	.orange:hover {
  		background-color: #FFCF75;
  		color: black;
	}

	footer {
  		position: absolute;
  		right: 0;
  		bottom: 0;
  		left: 0;
  		padding: 1rem;
  		background-color: #efefef;
  		text-align: center;
	}

	h1 {
	color: #FFFFFF;
	text-align: center;
	}

	nav ul li.icon {
		display: none;
	}

/*	Hiding overflowed text so that the rest of the design of the page wont be affected */
	@media screen and (max-width: 900px){
		section { 
			overflow: hidden;
			max-height: 400px;
		 }
	}
/* Overflowed text is being displayed using a scroll*/
	@media screen and (max-width:600px) {
		section {
			overflow-y: scroll;
			overflow-x: hidden;
			height: 500px;
		}
	}

</style>
</head>
<body>
<header>
	<h1>Initech layout task</h1>
</header>
<div class=".container">
	<nav id="mynav">
		<ul> 
			<li><a href="#">home</a></li>
			<li><a href="#">login</a></li>
			<li><a href="#">services</a></li>
			<li><a href="#">about</a></li>
			<li><a href="#">contact</a></li>
		</ul>
	</nav>
<section>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam vitae dui magna. Cras feugiat, mi eget lacinia facilisis, justo risus lacinia purus, at placerat dolor erat nec dui. Quisque sollicitudin odio quis arcu vehicula scelerisque. Nulla facilisi. Sed quis nulla id mauris tincidunt condimentum dignissim eu ipsum. Quisque iaculis nisi ut justo dapibus interdum. Suspendisse dictum turpis ac orci faucibus, et rhoncus lectus aliquet.</p>

		<p>Curabitur eu odio in ligula molestie interdum non at lorem. Pellentesque pellentesque ut ligula porttitor maximus. Morbi non neque erat. Nulla molestie ante nec varius faucibus. Suspendisse eleifend dolor eget gravida ultricies. </p>

		<p>Ut dictum posuere pulvinar. Curabitur condimentum fermentum eros et efficitur. Nam iaculis orci dictum lobortis porttitor. Donec accumsan, ex a convallis vestibulum, turpis nunc malesuada nunc, quis ornare augue quam sit amet ex. Quisque luctus leo vitae ante rhoncus, nec pharetra libero ullamcorper.</p>		
</section>
<button type="button" id="clickme" class="btn orange">Click me</button>
<footer>
	<p>Made by <strong>Orel Bloch</strong> 2016&copy;<p>
</footer>
</div>
<script> 
document.getElementById("clickme").addEventListener("click", function() {
	var navbar = document.getElementById("mynav");
	this.blur();
	// Show/hide navbar according to his current state.
	if (navbar.style.visibility === "hidden"  || navbar.style.visibility === "none"){
		navbar.style.visibility = "visible";
		var sections = document.getElementsByTagName("section");
		for (var i = 0; i < sections.length; i++) {
    		sections[i].style.marginLeft = "300px";
		}
	} else {
		navbar.style.visibility = "hidden";
		var sections = document.getElementsByTagName("section");
		for (var i = 0; i < sections.length; i++) {
    		sections[i].style.marginLeft = "0px";
    	}
	}
});
</script>
</body>
</html>

interview/templates/login.html
{% load bootstrap3 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Page</title>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
<div class="jumbotron" style="margin: auto; height: 100%;">
    <!--Login form. Input details exists in forms.py-->
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" value="Login" class="btn btn-default form-btn" >Login</button>
        {% endbuttons %}
    </form>
</div>
</body>
</html>

interview/templates/sorting.html
{% load  bootstrap3 %}
<html>
<head>
    <meta charset="UTF-8">
    <title>Sorting</title>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        .modal {
            display:    none;
            position:   fixed;
            z-index:    1000;
            top:        0;
            left:       0;
            height:     100%;
            width:      100%;
            background: rgba( 255, 255, 255, .8 )
            url('http://i.stack.imgur.com/FhHRx.gif')
            50% 50%
            no-repeat;
        }

        body.loading {
        overflow: hidden;
        }

        body.loading .modal {
        display: block;
        }

    </style>
</head>
<body>
<div class="jumbotron" style="margin: auto; text-align: center; width: 100%; height: 100%;">
<h1>Sorting numbers...</h1>
<form method="post">
    {% csrf_token %}
    <input type=text step=any name="num1" id="number" class="form-control" style="width: 40%; margin-left: 30%;"/><br/>
    {% buttons %}
    <br/>
    <button type="submit" class="btn btn-primary btn-lg">Send</button>
    {% endbuttons %}
    <button type="submit" class="btn btn-danger btn-md" ><a href="{% url 'interview:logout' %}">Logout</a></button>

</form>
<div id="divShow"></div>
<div class="modal"></div>
</div>
<script>
$(function() {
    $('form').submit(function(e) {
        //Preventing empty values being sent to the server
        if ($('#number').val() === "" ){
            alert("The field is empty");
            return false;
        }
        e.preventDefault();
        //Sends post request via ajax, including a csrf token, and represents the response in a div
        $.ajax({
            url: "",
            type: 'POST',
            csrfmiddlewaretoken: '{{ csrf_token }}',
            data: $('form').serialize(),
            dataType: "json",
            success: function(data) {
                $("#divShow").html(data.join(','));
            },
            error: function (request, status, error) {
                $("#divShow").html("Invalid data, try again");
            }
        });
    });
});
</script>
<script>
//Processing spinner script, loading starts when the request has been sent and stops when the response arrives.
$body = $("body");

$(document).on({
    ajaxStart: function() { $body.addClass("loading");    },
     ajaxStop: function() { $body.removeClass("loading"); }
});
</script>
</body>
</html>